### ISSUE TITLE
Gang Wars hangs on attract screen sequence

### ISSUE THREAD

**Issue by shuffle5** [va7deo/alpha68k#2]
It seems to crash, (hang) if you leave the title sequence running. Happened to me 3 times today every time I've used it today

**Comment by atrac17** [comment]
Please see if this issue occurs for you in the newest release. Can be grabbed from running Coin-Op Collection or the repo.

https://github.com/atrac17/Coin-Op_Collection/commit/35294b274d1cb736119106a7847690ed580f937f

**Comment by shuffle5** [comment]
Its been fixed now, thanks all. shall i post in any issues to coin op collection next time?
