### ISSUE TITLE
Some fixes/improvements

### ISSUE THREAD

**Issue by gyurco** [va7deo/alpha68k#4]
I tried to port this core to MiST. Meanwhile I also tried to solve the remaining issues, seems the core works well now. However I'm not sure I tested everything.
If interested, you can find my changes here:
https://github.com/gyurco/Mist_FPGA/tree/master/Arcade_MiST/Alpha%20Densi%20M68000%20Hardware

**Comment by atrac17** [comment]
We are going board by board and we're releasing two more games this week until I redump Gold Medalist for MAME but thanks!?!

**Comment by gyurco** [comment]
BTW the most interesting thing about Gold Medalist would be to check the MCU IRQ rate, as it directly affects the speed of the runners.
