### ISSUE TITLE
Time soldier - glitchy explosions

### ISSUE THREAD

**Issue by thehughhefner** [va7deo/alpha68k#5]
There seem to be sprite glitches when you defeat enemies. When things explode, the top left-hand corner shows glitchy explosions. 
Thank you so much for the core!

**Comment by atrac17** [comment]
Do you have the ability to record or can you screen and pause the behavior you are decribing?

**Comment by thehughhefner** [comment]
It seems to happen now and then. Need to setup my phone to record everything. I did notice this in the title screen: 
![image](https://user-images.githubusercontent.com/18329190/216577208-fe60d721-e375-4cf3-a752-b372f84e9d72.png)
This is with flip screen enabled

**Comment by atrac17** [comment]
> It seems to happen now and then. Need to setup my phone to record everything. I did notice this in the title screen: ![image](https://user-images.githubusercontent.com/18329190/216577208-fe60d721-e375-4cf3-a752-b372f84e9d72.png) This is with flip screen enabled

That's occurs on real hardware. I'm about 99% sure that what you are talking about with explosions is as well.
